In [1]:
import numpy as np

**Procesamiento de un Neurona Artificial**

Crear el vector de entrada X

In [2]:
X=np.array([[1],[0.5],[-0.6]])
print(X)

[[ 1. ]
 [ 0.5]
 [-0.6]]


Crear vector de pesos W

In [3]:
W=np.array([[1.0],[-0.7],[-1.0]])
print(W)

[[ 1. ]
 [-0.7]
 [-1. ]]


Calculo de la neta

In [4]:
Neta=(np.sum(np.multiply(X,W)))
print(Neta)

1.25


Function de activacion sigmoidal

In [5]:
Y=1.0/(1+np.exp(-Neta))
print(Y)

0.7772998611746911


**Procesamiento de una capa de Neuronas**

W y B matricial, Wp(4x3), B(3x1) y X(4x1)

In [6]:
Wp=np.array([[1.5,0.5, -0.5],[0.7,-0.8, 1.5],[-1.0,1.2, 0.3],[1.0,0.2,-0.3]])
print(Wp)
B=np.array([[0.7],[-0.3],[-0.5]])
print(B)
X=np.array([[1],[0.5],[-0.5],[1]])
print(X)

[[ 1.5  0.5 -0.5]
 [ 0.7 -0.8  1.5]
 [-1.   1.2  0.3]
 [ 1.   0.2 -0.3]]
[[ 0.7]
 [-0.3]
 [-0.5]]
[[ 1. ]
 [ 0.5]
 [-0.5]
 [ 1. ]]


**Neta matricial**

In [7]:
Neta=((np.matmul(np.transpose(Wp),X))+B)
print(Neta)

[[ 4.05]
 [-0.6 ]
 [-0.7 ]]


**Salida Matricial**

In [8]:
Y=1.0/(1+np.exp(-Neta))
print(Y)

[[0.98287597]
 [0.35434369]
 [0.33181223]]


**Implementación de otra capa de neuronas**

In [9]:
Wps=np.array([[1.5,0.5, -0.5,0.5, -0.5],[0.7,-0.8, 1.5,-0.8, 1.5],[-1.0,1.2, 0.3,-1.0,1.2]])
print(Wps)
Bs=np.array([[0.7],[-0.3],[-0.5],[-0.3],[-0.5]])
print(Bs)
print(Y)

[[ 1.5  0.5 -0.5  0.5 -0.5]
 [ 0.7 -0.8  1.5 -0.8  1.5]
 [-1.   1.2  0.3 -1.   1.2]]
[[ 0.7]
 [-0.3]
 [-0.5]
 [-0.3]
 [-0.5]]
[[0.98287597]
 [0.35434369]
 [0.33181223]]


In [10]:
Netas=((np.matmul(np.transpose(Wps),Y))+Bs)
print(Netas)

[[ 2.09054231]
 [ 0.3061377 ]
 [-0.36037877]
 [-0.4238492 ]
 [-0.06174777]]


In [11]:
#Salida con función de activación sigmoidal
Ys=1.0/(1+np.exp(-Netas))
print(Ys)

[[0.88998054]
 [0.57594224]
 [0.41086788]
 [0.39559604]
 [0.48456796]]


In [12]:
#Salida con función de activación Tangentge hiperbólica sigmoidal
Ys=((np.exp(Netas) - np.exp(-Netas))/(np.exp(Netas) + np.exp(-Netas)))
print(Ys)

[[ 0.9698962 ]
 [ 0.29691935]
 [-0.34554763]
 [-0.40016821]
 [-0.06166941]]
